from django.urls import path
from .views import *
urlpatterns = [
  path('checkenv',check_env),
  path('test-storage/', test_storage),
  path('test-cloud/', test_cloudinary),
  path('', index, name="index"),
  path('about/', about, name="about"),
  path('address/', address, name="address"),
  path('category/', category, name="category"),
  path('cart/', cart, name='cart'),                                     
  path('add-to-cart/<int:id>/', add_to_cart, name='add_to_cart'),
  path('remove-from-cart/<int:id>/', remove_from_cart, name='remove_from_cart'),
  path('dashboard/categoryform/', categoryform, name="categoryform"),
  path('dashboard/productform/', productform, name="productform"),
  path('contact/', contact, name="contact"),
  path('done/', done, name="done"),
  path('edit/', edit, name="edit"),
  path('faq/', faq, name="faq"),
  path('logout/', user_logout, name="logout"),
  path('dashboard/', dashboard, name="dashboard"),
  path('login/', user_login, name="login"),
  path('order_summary/', order_summary, name="order_summary"),
  path('password/', password, name="password"),
  path('payment_method/', payment_method, name="payment_method"),
  path('place-order/', place_order, name='place_order'),
  path('privacy/', privacy, name="privacy"),
  path('product/<int:id>/', product, name="product"), 
  path('productlist1/', productlist1, name="productlist1"),
  path('buy-now/<int:id>/', buy_now, name='buy_now'),
  path('profile/', profile, name="profile"),
  path('registration/', registration, name="registration"),
  path('review/', review, name="review"),
  path('review_form/', review_form, name="review_form"),
  path('search/', search, name="search"),
  path('terms/', terms, name="terms"),
  path('wish/', wish, name="wish"),
  path('products/<int:id>/', product_by_category, name='product_by_category'),
  path('add-wishlist/<int:id>/', add_to_wishlist, name='add_wishlist'),
  path('remove-wishlist/<int:id>/', remove_from_wishlist, name='remove_wishlist'),
  path('admin_logout/', admin_logout, name="admin_logout"),
  path('adminlogin/',adminlogin,name="adminlogin"),
  path('forgot-password/', password_reset_request, name='password_reset_request'),
  path('reset-password/<uuid:token>/', password_reset_confirm, name='password_reset_confirm'),
  path('dashboard/users/', admin_users, name='admin_users'),
  path('dashboard/contacts/', admin_contacts, name='admin_contacts'),
]

